defaults:
    - override hydra/launcher: submitit_local

# environment
# task: dog-run
# task: humanoid-run
# task: walker-run
# task: cartpole-balance
task: myo-reach
# task: myo-pose
# task: myo-obj-hold
# task: lift-cube
# task: mw-button-press
obs: state
boom: v1
update_flow: true
extra: ""
compile: true

# environment type: dm_control, myosuite, humanoid, gym, maniskill, metaworld
# env_type: dm_control
env_type: myosuite
# env_type: maniskill
# env_type: metaworld

# evaluation
checkpoint: ???
eval_episodes: 10
eval_pi: true
eval_diffusion: false
eval_value: false
eval_freq: 50000

# training
steps: 1_001_000 # env step = steps * action_repeat
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
data_dir: ???
exp_name: default

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 24
num_flow_trajs: 48
horizon: 3
min_std: 0.05
max_std: 2
temperature: 0.5

# flow
flow_q_coef: 0.0
flow_weight_max: 1.0  # max weight for Q-based weighting
flow_weight_min: 0.001   # min weight for Q-based weighting

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: ???
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
num_v: 5
dropout: 0.01
simnorm_dim: 8

# logging
# wandb_project: boom-multi-q
wandb_project: flow
wandb_entity: shallowdream0745-thu

wandb_silent: false
disable_wandb: false
save_csv: true

# misc
save_video: false
save_agent: true
save_freq: 500000
seed: 1

# convenience
work_dir: ???
task_title: ???
multitask: false
tasks: ???
obs_shape: ???
action_dim: ???
episode_length: ???
obs_shapes: ???
action_dims: ???
episode_lengths: ???
seed_steps: 1000
bin_size: ???

# humanoid envs
policy_path: ???
mean_path: ???
var_path: ???
policy_type: ???
small_obs: ???
